name : markdown-to-html
on :
  push :
    branches:
      - main
    paths :
      - "src/arc/**"
jobs :
  convert_md :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v4
      - run : sudo apt install tree  pandoc -y
      - run cd src/arc
      - run : for file in `find . -maxdepth 1 -name '*.md'`; do echo $file; pandoc $file -s -o $HOME/public/$(basename $file .md).html; done
      - run : cd && tree
      - run : git config user.name  "roistaff"
      - run : git config user.email "roistaff1983@gmail.com"
      - run : git add .
      - run : git commit -m "generated"
      - run : git push
      - run : ls && tree
