name : markdown-to-html
on :
  push :
    branches:
      - main
    paths :
      - "src/arc/**"
jobs :
  convert_md :
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v4
      - run : sudo apt install pandoc git -y
      - run : pandoc --version
      - run : git diff --name-only origin/main...HEAD
